/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StayRouteImport } from './routes/stay'
import { Route as MapLunjaRouteImport } from './routes/map-lunja'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const MapLunjaRoute = MapLunjaRouteImport.update({
  id: '/map-lunja',
  path: '/map-lunja',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/map-lunja': typeof MapLunjaRoute
  '/stay': typeof StayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/map-lunja': typeof MapLunjaRoute
  '/stay': typeof StayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/map-lunja': typeof MapLunjaRoute
  '/stay': typeof StayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/experience' | '/map-lunja' | '/stay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/experience' | '/map-lunja' | '/stay'
  id: '__root__' | '/' | '/contact' | '/experience' | '/map-lunja' | '/stay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  MapLunjaRoute: typeof MapLunjaRoute
  StayRoute: typeof StayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-lunja': {
      id: '/map-lunja'
      path: '/map-lunja'
      fullPath: '/map-lunja'
      preLoaderRoute: typeof MapLunjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  MapLunjaRoute: MapLunjaRoute,
  StayRoute: StayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
